### ISSUE TITLE
PureScript on Docker guide

### ISSUE THREAD

**Issue by hdgarrood** [ChristopherBiscardi/purescript#2]
Hi, I'm in the process of cleaning up the purescript wiki a bit, and I think you wrote a page titled "PureScript on Docker" originally. I don't think it quite fits with what we're aiming to turn the wiki into, so I've preserved it in a gist in case you ever wanted to do anything with it. If not, feel free to close and ignore this. Cheers!

https://gist.github.com/hdgarrood/65bef79ccdc8dcc9941d00de369372f1

**Comment by ChristopherBiscardi** [comment]
Cheers. That content looks really out of date anyway. I forked it into my account for posterity.
